# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= POSTGRES_USER='rodrigo' %>
  password: <%= POSTGRES_PASSWORD='RFCupIwMkP900fJn8H5nqnzwiozGYmsd' %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database:  <%= ENV['POSTGRES_TEST_DB'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>